### ISSUE TITLE
ctr: not found

### ISSUE THREAD

**Issue by tamsky** [mariusgrigaitis/docker-mac-ssh-auth-sock#2]
where does the `ctr` binary/script, in use in your script, originate?

**Comment by tamsky** [comment]
`ctr` used at:

https://github.com/mariusgrigaitis/docker-mac-ssh-auth-sock/commit/809a97434ef90a56f8e07fb031874a01f040fa2d#diff-81f69eb1c25723970f397f12edd4721bR49

**Comment by mariusgrigaitis** [comment]
`ctr` is from containerd I assume.

https://github.com/projectatomic/containerd/blob/master/docs/cli.md

It comes "inside" the docker for mac VM since it's built using linuxkit https://github.com/linuxkit/linuxkit

You can connect to VM's tty using 
```
screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
```
